apiVersion: v1
kind: Service
metadata:
  name: redis # Sets service name
  labels:
    app: redis # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 6379 # Sets port to run the postgres application
  selector:
    app: redis